import { Injectable } from '@angular/core';
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
import {
  PoComboFilter,
  PoComboOption,
  PoLookupFilter,
  PoLookupFilteredItemsParams,
  PoLookupResponseApi,
} from '@po-ui/ng-components';
import { Observable, map, of } from 'rxjs';
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
import {
	PoComboFilter,
	PoComboOption,
	PoLookupFilter,
	PoLookupFilteredItemsParams,
	PoLookupResponseApi,
} from '@po-ui/ng-components';
import { Observable, map, of } from 'rxjs';
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
import { ApiService } from '../api.service';
import { HttpParams, HttpClient } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';

/**
 * Todos os combos que apontam para API
 */

/**
 * Estrutura de Retorno do Adaptor. Fixado para não haver manipulação ou inclusão de novos elementos
 * Sem que o desenvolvedor tenha de alterar aqui.
 * @
 * Ao alterar essa classe, verificar os locais aonde é utilizado o adaptor.
 */
export class AdaptorReturnStruct implements PoComboOption {
  value: string = '';
  label: string = '';
  cpf: string = '';
}

export class FilterComboStruct implements PoComboOption {
  label: string = '';
  value: string = '';
  desc: string = '';
}

export class EstadoComboStruct implements PoComboOption {
  label: string = '';
  value: string = '';
  uf: string = '';
}

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
export class TarifaComboStruct implements PoComboOption {
  label: string = '';
  value: string = '';
  desc: string = '';
}

export class OrgaoConcessorPoLookUpService implements PoComboOption {
  label: string = '';
  value: string = '';
  desc: string = '';
}
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
export class TarifaComboStruct implements PoComboOption {
	label: string = '';
	value: string = '';
	desc: string = '';
}

export class OrgaoConcessorPoLookUpService implements PoComboOption {
	label: string = '';
	value: string = '';
	desc: string = '';
}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

@Injectable({
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  providedIn: 'root',
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
	providedIn: 'root',
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
})
export class MatriculaComboService implements PoComboFilter {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  private endpoint: string = 'FRETAMENTOURBANO/matricula';

  constructor(
    private apiService: ApiService,
    private route: ActivatedRoute
  ) {}

  getFilteredData(
    params: any,
    filterParams?: any
  ): Observable<AdaptorReturnStruct[]> {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
	private endpoint: string = 'FRETAMENTOURBANO/matricula';

	constructor(
		private apiService: ApiService	) { }

	getFilteredData(
		params: any,
		filterParams?: any
	): Observable<AdaptorReturnStruct[]> {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
    let httpParams = new HttpParams();

    let filter: string = '';

    if (params.value != '')
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
      filter =
        "AND UPPER(RA_MAT) LIKE '%" +
        params.value +
        "%' OR UPPER(RA_CIC) LIKE '%" +
        params.value +
        "%'OR UPPER(RA_NOME) LIKE '%" +
        params.value +
        "%'";

    filter =
      "UPPER(RA_MAT) LIKE '%" +
      params.value +
      "%' OR UPPER(RA_CIC) LIKE '%" +
      params.value +
      "%'OR UPPER(RA_NOME) LIKE '%" +
      params.value +
      "%'";
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
			filter =
				"AND UPPER(RA_MAT) LIKE '%" +
				params.value +
				"%' OR UPPER(RA_CIC) LIKE '%" +
				params.value +
				"%'OR UPPER(RA_NOME) LIKE '%" +
				params.value +
				"%'";
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

    httpParams = httpParams.append('FILTER', filter);
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    httpParams = httpParams.append('FIELDEMPTY', true);
    httpParams = httpParams.append('FIELDVIRTUAL', true);

    return this.apiService.get(this.endpoint, httpParams).pipe(
      map((response: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		httpParams = httpParams.append('FIELDEMPTY', true);
		httpParams = httpParams.append('FIELDVIRTUAL', true);

		return this.apiService.get(this.endpoint, httpParams).pipe(
			map((response: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        const items: AdaptorReturnStruct[] = [];
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				const items: AdaptorReturnStruct[] = [];
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        let hasNext = true;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				let hasNext = true;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        response.Matricula.forEach((resource: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				response.Matricula.forEach((resource: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          let itemReturn: AdaptorReturnStruct = new AdaptorReturnStruct();
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					let itemReturn: AdaptorReturnStruct = new AdaptorReturnStruct();
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          itemReturn.value = resource.matricula;
          itemReturn.label = resource.nome;
          itemReturn.cpf = resource.cic;

          items.push(itemReturn);

          if (params.page * params.pageSize >= response.total) {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					itemReturn.value = resource.matricula;
					itemReturn.label = resource.nome;
					itemReturn.cpf = resource.cic;

					items.push(itemReturn);

					if (params.page * params.pageSize >= response.total) {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
            hasNext = false;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
						hasNext = false;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        });

        return items;
      })
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				});

				return items;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
      })
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    );
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		);
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
  }

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  getObjectByValue(
    value: string | number,
    filterParams?: any
  ): Observable<PoComboOption> {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
	getObjectByValue(
		value: string | number,
		filterParams?: any
	): Observable<PoComboOption> {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
    let params = new HttpParams();

    let filter: string = `AND RA_MAT='${value}'`;

    if (filterParams != undefined) {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
      filter += ' AND ' + filterParams;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
			filter += ' AND ' + filterParams;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
    }
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    params = params.append('FILTER', filter);

    return this.apiService.get(this.endpoint, params).pipe(
      map((response: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		params = params.append('FILTER', filter);

		return this.apiService.get(this.endpoint, params).pipe(
			map((response: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        let itemReturn = new AdaptorReturnStruct();
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				let itemReturn = new AdaptorReturnStruct();
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        itemReturn.value = response.Matricula[0].matricula;
        itemReturn.label = response.Matricula[0].nome;
        itemReturn.cpf = response.Matricula[0].cic;

        return itemReturn;
      })
    );
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				itemReturn.value = response.Matricula[0].matricula;
				itemReturn.label = response.Matricula[0].nome;
				itemReturn.cpf = response.Matricula[0].cic;

				return itemReturn;
			})
		);
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
  }
}

/**
 * localComboService
 * Utilizado no combo de Local
 */
@Injectable({
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  providedIn: 'root',
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
	providedIn: 'root',
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
})
export class localComboService implements PoComboFilter {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  private endpoint: string = 'FRETAMENTOURBANO/local';

  constructor(private apiService: ApiService) {}

  getFilteredData(
    params: any,
    filterParams?: any
  ): Observable<FilterComboStruct[]> {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
	private endpoint: string = 'FRETAMENTOURBANO/local';

	constructor(private apiService: ApiService) { }

	getFilteredData(
		params: any,
		filterParams?: any
	): Observable<FilterComboStruct[]> {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
    let httpParams = new HttpParams();
    let filter: string = '';

    if (filterParams) {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
      filter = filterParams;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
			filter = filterParams;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
    }

    if (params.value != '') {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
      filter =
        " AND (UPPER(GI1_COD) LIKE UPPER('%" +
        params.value +
        "%') OR " +
        " UPPER(GI1_DESCRI) LIKE UPPER('%" +
        params.value +
        "%') ) ";
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
			filter =
				" AND (UPPER(GI1_COD) LIKE UPPER('%" +
				params.value +
				"%') OR " +
				" UPPER(GI1_DESCRI) LIKE UPPER('%" +
				params.value +
				"%') ) ";
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
    }

    httpParams = httpParams.append('filter', filter);

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    return this.apiService.get(this.endpoint, httpParams).pipe(
      map((response: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		return this.apiService.get(this.endpoint, httpParams).pipe(
			map((response: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        const items: FilterComboStruct[] = [];
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				const items: FilterComboStruct[] = [];
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        let hasNext = true;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				let hasNext = true;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        response.Localidade.forEach((resource: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				response.Localidade.forEach((resource: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          let itemReturn: FilterComboStruct = new FilterComboStruct();
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					let itemReturn: FilterComboStruct = new FilterComboStruct();
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          itemReturn.value = resource.codLocal;
          itemReturn.label = resource.descLocal;
          itemReturn.desc = resource.codMuni;

          items.push(itemReturn);
        });
        return items;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					itemReturn.value = resource.codLocal;
					itemReturn.label = resource.descLocal;
					itemReturn.desc = resource.codMuni;

					items.push(itemReturn);
				});
				return items;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
      })
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    );
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		);
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
  }

  getObjectByValue(): Observable<PoComboOption> {
    let params = new HttpParams();

    let filter: string = ``;

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    params = params.append('FILTER', filter);

    return this.apiService.get(this.endpoint, params).pipe(
      map((response: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		params = params.append('FILTER', filter);

		return this.apiService.get(this.endpoint, params).pipe(
			map((response: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        let itemReturn = new FilterComboStruct();
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				let itemReturn = new FilterComboStruct();
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        itemReturn.value = response.codLocal;
        itemReturn.label = response.descLocal;
        itemReturn.desc = response.codMuni;

        return itemReturn;
      })
    );
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				itemReturn.value = response.codLocal;
				itemReturn.label = response.descLocal;
				itemReturn.desc = response.codMuni;

				return itemReturn;
			})
		);
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
  }
}

/**
 * muniComboService
 * Utilizado no combo de municipio
 */
@Injectable({
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  providedIn: 'root',
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
	providedIn: 'root',
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
})
export class muniComboService implements PoComboFilter {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  private endpoint: string = 'FRETAMENTOURBANO/municipio';

  constructor(private apiService: ApiService) {}

  getFilteredData(
    params: any,
    filterParams: any
  ): Observable<FilterComboStruct[]> {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
	private endpoint: string = 'FRETAMENTOURBANO/municipio';

	constructor(private apiService: ApiService) { }

	getFilteredData(
		params: any,
		filterParams: any
	): Observable<FilterComboStruct[]> {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
    let httpParams = new HttpParams();
    let filter: string = '';

    if (filterParams) {
      filter = filterParams;
    }

    if (params.value != '')
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
      filter =
        " AND (UPPER(GI1_CDMUNI) LIKE UPPER('%" +
        params.value +
        "%') OR " +
        " UPPER(GI1_DSMUNI) LIKE UPPER('%" +
        params.value +
        "%') ) ";
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
			filter =
				" AND (UPPER(GI1_CDMUNI) LIKE UPPER('%" +
				params.value +
				"%') OR " +
				" UPPER(GI1_DSMUNI) LIKE UPPER('%" +
				params.value +
				"%') ) ";
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

    httpParams = httpParams.append('FILTER', filter);

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    return this.apiService.get(this.endpoint, httpParams).pipe(
      map((response: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		return this.apiService.get(this.endpoint, httpParams).pipe(
			map((response: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        const items: FilterComboStruct[] = [];
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				const items: FilterComboStruct[] = [];
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        let hasNext = true;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				let hasNext = true;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        response.Municipio.forEach((resource: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				response.Municipio.forEach((resource: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          let itemReturn: FilterComboStruct = new FilterComboStruct();
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					let itemReturn: FilterComboStruct = new FilterComboStruct();
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          itemReturn.value = resource.codMuni;
          itemReturn.label = resource.descMuni;
          itemReturn.desc = resource.uf;

          items.push(itemReturn);
        });
        return items;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					itemReturn.value = resource.codMuni;
					itemReturn.label = resource.descMuni;
					itemReturn.desc = resource.uf;

					items.push(itemReturn);
				});
				return items;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
      })
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    );
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		);
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
  }

  getObjectByValue(): Observable<PoComboOption> {
    let params = new HttpParams();
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    return this.apiService.get(this.endpoint, params).pipe(
      map(() => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		return this.apiService.get(this.endpoint, params).pipe(
			map(() => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        let itemReturn = new AdaptorReturnStruct();
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				let itemReturn = new AdaptorReturnStruct();
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        itemReturn.value = '';
        itemReturn.label = '';
        itemReturn.cpf = '';

        return itemReturn;
      })
    );
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				itemReturn.value = '';
				itemReturn.label = '';
				itemReturn.cpf = '';

				return itemReturn;
			})
		);
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
  }
}

/**
 * comboFormService
 * Utilizado no combo de municipio
 */
@Injectable({
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  providedIn: 'root',
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
	providedIn: 'root',
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
})
export class comboFormService implements PoComboFilter {
  private endpoint: string = 'FRETAMENTOURBANO/estadoMun';
  private filterUf: string = '';

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  constructor(private apiService: ApiService) {}

  getFilteredData(
    params: any,
    filterParams: any
  ): Observable<EstadoComboStruct[]> {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================

	constructor(private apiService: ApiService) { }

	getFilteredData(
		params: any,
		filterParams: any
	): Observable<EstadoComboStruct[]> {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
    let httpParams = new HttpParams();
    let filter: string = '';

    if (typeof filterParams === 'boolean' && true) {
      httpParams = httpParams.set('lUf', filterParams);
      if (params.value != '') {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        filter = " AND (UPPER(CC2_EST) LIKE UPPER('%" + params.value + "%')) ";
      }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				filter = " AND (UPPER(CC2_EST) LIKE UPPER('%" + params.value + "%')) ";
			}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
    } else {
      if (filterParams) {
        filter = filterParams;
      }

      if (params.value != '') {
        if (filter != '') {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          filter +=
            " AND (UPPER(CC2_MUN) LIKE UPPER('%" + params.value + "')) ";
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					filter +=
						" AND (UPPER(CC2_MUN) LIKE UPPER('" + params.value + "%') OR UPPER(CC2_CODMUN) LIKE UPPER('%" + params.value + "%')) ";
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
        } else {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          filter = " AND (UPPER(CC2_MUN) LIKE UPPER('%" + params.value + "')) ";
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					filter = " AND (UPPER(CC2_MUN) LIKE UPPER('" + params.value + "%') OR UPPER(CC2_CODMUN) LIKE UPPER('%" + params.value + "%')) ";
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
      }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
			}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

    httpParams = httpParams.append('FILTER', filter);

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    return this.apiService.get(this.endpoint, httpParams).pipe(
      map((response: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		return this.apiService.get(this.endpoint, httpParams).pipe(
			map((response: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        const items: EstadoComboStruct[] = [];
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				const items: EstadoComboStruct[] = [];
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        response.EstadoMun.forEach((resource: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				response.EstadoMun.forEach((resource: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          let itemReturn: EstadoComboStruct = new EstadoComboStruct();
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					let itemReturn: EstadoComboStruct = new EstadoComboStruct();
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          if (typeof filterParams === 'boolean') {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					if (typeof filterParams === 'boolean') {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
            itemReturn.value = resource.uf;
            itemReturn.label = resource.uf;
            itemReturn.uf = resource.uf;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
						itemReturn.value = resource.uf;
						itemReturn.label = resource.uf;
						itemReturn.uf = resource.uf;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          } else {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					} else {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
            itemReturn.value = resource.codigo;
            itemReturn.label = resource.municipio;
            itemReturn.uf = resource.uf;

            itemReturn.value = resource.codMuni;
            itemReturn.label = resource.descMuni;
            itemReturn.uf = resource.uf;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
						itemReturn.value = resource.codigo;
						itemReturn.label = resource.municipio;
						itemReturn.uf = resource.uf;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          items.push(itemReturn);
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					items.push(itemReturn);
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        });
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				});
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        return items;
      })
    );
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				return items;
			})
		);
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
  }

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  getObjectByValue(
    value: string | number,
    filterParams?: any
  ): Observable<PoComboOption> {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
	getObjectByValue(
		value: string | number,
		filterParams?: any
	): Observable<PoComboOption> {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
    let params = new HttpParams();
    let filter: string = ``;

    if (typeof filterParams === 'boolean' && filterParams) {
      params = params.set('lUf', filterParams);
      filter = `AND(UPPER(CC2_EST) LIKE UPPER('%${value}'))`;
    } else {
      filter = `AND(UPPER(CC2_CODMUN) LIKE UPPER('%${value}') ${this.filterUf} `;
    }

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    params = params.append('FILTER', filter);

    return this.apiService.get(this.endpoint, params).pipe(
      map((response: any) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		params = params.append('FILTER', filter);

		return this.apiService.get(this.endpoint, params).pipe(
			map((response: any) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        let itemReturn = new EstadoComboStruct();
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				let itemReturn = new EstadoComboStruct();
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        if (typeof filterParams === 'boolean') {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				if (typeof filterParams === 'boolean') {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          itemReturn.value = response.EstadoMun[0].uf;
          itemReturn.label = response.EstadoMun[0].uf;
          itemReturn.uf = response.EstadoMun[0].uf;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					itemReturn.value = response.EstadoMun[0].uf;
					itemReturn.label = response.EstadoMun[0].uf;
					itemReturn.uf = response.EstadoMun[0].uf;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
        } else {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
				} else {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
          itemReturn.value = response.EstadoMun[0].codigo;
          itemReturn.label = response.EstadoMun[0].municipio;
          itemReturn.uf = response.EstadoMun[0].uf;
        }

        return itemReturn;
      })
    );
  }

  setFilterUf(value: string) {
    this.filterUf = value;
  }
}

@Injectable({
  providedIn: 'root',
})
export class TarifaComboService implements PoComboFilter {
  private endpoint: string = 'FRETAMENTOURBANO/local';

  constructor(private apiService: ApiService) {}

  getFilteredData(
    params: any,
    filterParams?: any
  ): Observable<TarifaComboStruct[]> {
    let httpParams = new HttpParams();
    let filter: string = '';

    if (filterParams) {
      filter = filterParams;
    }

    if (params.value != '') {
      filter =
        " AND (UPPER(GI1_COD) LIKE UPPER('%" +
        params.value +
        "%') OR " +
        " UPPER(GI1_DESCRI) LIKE UPPER('%" +
        params.value +
        "%') ) ";
    }

    httpParams = httpParams.append('filter', filter);

    let items: TarifaComboStruct[] = [];
    items = [
      { label: '0001 - Tarifa 1', value: '0001', desc: 'Tarifa 1' },
      { label: '0002 - Tarifa 2', value: '0002', desc: 'Tarifa 2' },
      { label: '0003 - Tarifa 3', value: '0003', desc: 'Tarifa 3' },
    ];

    // return of(items);
    return this.apiService.get(this.endpoint, httpParams).pipe(
      map((response: any) => {
        const items: FilterComboStruct[] = [];
        let hasNext = true;

        response.Localidade.forEach((resource: any) => {
          let itemReturn: FilterComboStruct = new FilterComboStruct();

          itemReturn.value = resource.codLocal;
          itemReturn.label = resource.descLocal;
          itemReturn.desc = resource.codMuni;

          items.push(itemReturn);

          if (params.page * params.pageSize >= response.total) {
            hasNext = false;
          }
        });
        return items;
      })
    );
  }

  getObjectByValue(
    value: string | number,
    filterParams?: any
  ): Observable<PoComboOption> {
    let params = new HttpParams();

    let filter: string = ``;

    params = params.append('FILTER', filter);

    return this.apiService.get(this.endpoint, params).pipe(
      map((response: any) => {
        let itemReturn = new FilterComboStruct();

        itemReturn.value = response.codLocal;
        itemReturn.label = response.descLocal;
        itemReturn.desc = response.codMuni;

        return itemReturn;
      })
    );
  }
}

@Injectable({
  providedIn: 'root',
})
export class OrgaoConcessorComboService implements PoComboFilter {
  private endpoint: string = 'FRETAMENTOURBANO/local';

  constructor(private apiService: ApiService) {}

  getFilteredData(
    params: any,
    filterParams?: any
  ): Observable<TarifaComboStruct[]> {
    let httpParams = new HttpParams();
    let filter: string = '';

    if (filterParams) {
      filter = filterParams;
    }

    if (params.value != '') {
      filter =
        " AND (UPPER(GI1_COD) LIKE UPPER('%" +
        params.value +
        "%') OR " +
        " UPPER(GI1_DESCRI) LIKE UPPER('%" +
        params.value +
        "%') ) ";
    }

    httpParams = httpParams.append('filter', filter);

    return this.apiService.get(this.endpoint, httpParams).pipe(
      map((response: any) => {
        const items: FilterComboStruct[] = [];
        let hasNext = true;

        response.Localidade.forEach((resource: any) => {
          let itemReturn: FilterComboStruct = new FilterComboStruct();

          itemReturn.value = resource.codLocal;
          itemReturn.label = resource.descLocal;
          itemReturn.desc = resource.codMuni;

          items.push(itemReturn);

          if (params.page * params.pageSize >= response.total) {
            hasNext = false;
          }
        });
        return items;
      })
    );
  }

  getObjectByValue(
    value: string | number,
    filterParams?: any
  ): Observable<PoComboOption> {
    let params = new HttpParams();

    let filter: string = ``;

    params = params.append('FILTER', filter);

    return this.apiService.get(this.endpoint, params).pipe(
      map((response: any) => {
        let itemReturn = new FilterComboStruct();

        itemReturn.value = response.codLocal;
        itemReturn.label = response.descLocal;
        itemReturn.desc = response.codMuni;

        return itemReturn;
      })
    );
  }
}

@Injectable({
  providedIn: 'root',
})
export class poLookUpOrgaoConcessor implements PoLookupFilter {
  // private endpoint: string = 'FRETAMENTOURBANO/local';
  private endpoint: string = 'https://po-sample-api.onrender.com/v1/heroes';

  constructor(
    private apiService: ApiService,
    private _http: HttpClient
  ) {}

  getObjectByValue(value: any): Observable<any> {
    return this.apiService.get(this.endpoint, value);
  }

  getFilteredItems(
    filteredParams: PoLookupFilteredItemsParams
  ): Observable<any> {
    const { filterParams, advancedFilters, ...restFilteredItemsParams } =
      filteredParams;
    const params = {
      ...restFilteredItemsParams,
      ...filterParams,
      ...advancedFilters,
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
					itemReturn.value = response.EstadoMun[0].codigo;
					itemReturn.label = response.EstadoMun[0].municipio;
					itemReturn.uf = response.EstadoMun[0].uf;
				}

				return itemReturn;
			})
		);
	}

	setFilterUf(value: string) {
		this.filterUf = value;
	}
}

@Injectable({
	providedIn: 'root',
})
export class TarifaComboService implements PoComboFilter {
	private endpoint: string = 'FRETAMENTOURBANO/local';

	constructor(private apiService: ApiService) { }

	getFilteredData(
		params: any,
		filterParams?: any
	): Observable<TarifaComboStruct[]> {
		let httpParams = new HttpParams();
		let filter: string = '';

		if (filterParams) {
			filter = filterParams;
		}

		if (params.value != '') {
			filter =
				" AND (UPPER(GI1_COD) LIKE UPPER('%" +
				params.value +
				"%') OR " +
				" UPPER(GI1_DESCRI) LIKE UPPER('%" +
				params.value +
				"%') ) ";
		}

		httpParams = httpParams.append('filter', filter);

		let items: TarifaComboStruct[] = [];
		items = [
			{ label: '0001 - Tarifa 1', value: '0001', desc: 'Tarifa 1' },
			{ label: '0002 - Tarifa 2', value: '0002', desc: 'Tarifa 2' },
			{ label: '0003 - Tarifa 3', value: '0003', desc: 'Tarifa 3' },
		];

		// return of(items);
		return this.apiService.get(this.endpoint, httpParams).pipe(
			map((response: any) => {
				const items: FilterComboStruct[] = [];
				let hasNext = true;

				response.Localidade.forEach((resource: any) => {
					let itemReturn: FilterComboStruct = new FilterComboStruct();

					itemReturn.value = resource.codLocal;
					itemReturn.label = resource.descLocal;
					itemReturn.desc = resource.codMuni;

					items.push(itemReturn);

					if (params.page * params.pageSize >= response.total) {
						hasNext = false;
					}
				});
				return items;
			})
		);
	}

	getObjectByValue(
		value: string | number,
		filterParams?: any
	): Observable<PoComboOption> {
		let params = new HttpParams();

		let filter: string = ``;

		params = params.append('FILTER', filter);

		return this.apiService.get(this.endpoint, params).pipe(
			map((response: any) => {
				let itemReturn = new FilterComboStruct();

				itemReturn.value = response.codLocal;
				itemReturn.label = response.descLocal;
				itemReturn.desc = response.codMuni;

				return itemReturn;
			})
		);
	}
}

@Injectable({
	providedIn: 'root',
})
export class OrgaoConcessorComboService implements PoComboFilter {
	private endpoint: string = 'FRETAMENTOURBANO/local';

	constructor(private apiService: ApiService) { }

	getFilteredData(
		params: any,
		filterParams?: any
	): Observable<TarifaComboStruct[]> {
		let httpParams = new HttpParams();
		let filter: string = '';

		if (filterParams) {
			filter = filterParams;
		}

		if (params.value != '') {
			filter =
				" AND (UPPER(GI1_COD) LIKE UPPER('%" +
				params.value +
				"%') OR " +
				" UPPER(GI1_DESCRI) LIKE UPPER('%" +
				params.value +
				"%') ) ";
		}

		httpParams = httpParams.append('filter', filter);

		return this.apiService.get(this.endpoint, httpParams).pipe(
			map((response: any) => {
				const items: FilterComboStruct[] = [];
				let hasNext = true;

				response.Localidade.forEach((resource: any) => {
					let itemReturn: FilterComboStruct = new FilterComboStruct();

					itemReturn.value = resource.codLocal;
					itemReturn.label = resource.descLocal;
					itemReturn.desc = resource.codMuni;

					items.push(itemReturn);

					if (params.page * params.pageSize >= response.total) {
						hasNext = false;
					}
				});
				return items;
			})
		);
	}

	getObjectByValue(
		value: string | number,
		filterParams?: any
	): Observable<PoComboOption> {
		let params = new HttpParams();

		let filter: string = ``;

		params = params.append('FILTER', filter);

		return this.apiService.get(this.endpoint, params).pipe(
			map((response: any) => {
				let itemReturn = new FilterComboStruct();

				itemReturn.value = response.codLocal;
				itemReturn.label = response.descLocal;
				itemReturn.desc = response.codMuni;

				return itemReturn;
			})
		);
	}
}

@Injectable({
	providedIn: 'root',
})
export class poLookUpOrgaoConcessor implements PoLookupFilter {
	// private endpoint: string = 'FRETAMENTOURBANO/local';
	private endpoint: string = 'https://po-sample-api.onrender.com/v1/heroes';

	constructor(
		private apiService: ApiService,
		private _http: HttpClient
	) { }

	getObjectByValue(value: any): Observable<any> {
		return this.apiService.get(this.endpoint, value);
	}

	getFilteredItems(
		filteredParams: PoLookupFilteredItemsParams
	): Observable<any> {
		const { filterParams, advancedFilters, ...restFilteredItemsParams } =
			filteredParams;
		const params = {
			...restFilteredItemsParams,
			...filterParams,
			...advancedFilters,
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    };
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		};
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    return this._http.get(this.endpoint, params);
  }
}

@Injectable({
  providedIn: 'root',
})
export class poLookUpFormasDePagamento implements PoLookupFilter {
  // private endpoint: string = 'FRETAMENTOURBANO/local';
  private endpoint: string = 'https://po-sample-api.onrender.com/v1/heroes';

  constructor(
    private apiService: ApiService,
    private _http: HttpClient
  ) {}

  getObjectByValue(value: any): Observable<any> {
    return this.apiService.get(this.endpoint, value);
  }

  getFilteredItems(
    filteredParams: PoLookupFilteredItemsParams
  ): Observable<any> {
    const { filterParams, advancedFilters, ...restFilteredItemsParams } =
      filteredParams;
    const params = {
      ...restFilteredItemsParams,
      ...filterParams,
      ...advancedFilters,
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		return this._http.get(this.endpoint, params);
	}
}

@Injectable({
	providedIn: 'root',
})
export class poLookUpFormasDePagamento implements PoLookupFilter {
	// private endpoint: string = 'FRETAMENTOURBANO/local';
	private endpoint: string = 'https://po-sample-api.onrender.com/v1/heroes';

	constructor(
		private apiService: ApiService,
		private _http: HttpClient
	) { }

	getObjectByValue(value: any): Observable<any> {
		return this.apiService.get(this.endpoint, value);
	}

	getFilteredItems(
		filteredParams: PoLookupFilteredItemsParams
	): Observable<any> {
		const { filterParams, advancedFilters, ...restFilteredItemsParams } =
			filteredParams;
		const params = {
			...restFilteredItemsParams,
			...filterParams,
			...advancedFilters,
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    };
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		};
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
    return this._http.get(this.endpoint, params);
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
		return this._http.get(this.endpoint, params);
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> DSERGTP-9726
  }
}
